DigiManager:

    NoInternet:
        id:nointernet
        name:'nointernet'
    Login:
        id:login
        name:'login'
    
    Home:
        id:home
        name:'home'
        HomeDrawer:
            id:home_drawer
            state:'close'
            color:1,1,1,1
            radius:[0,0,20,0]
            size_hint_y:1
            padding:[15,35,10,10]
            scrim_color:0,0,0,.75
            opening_time:.1
            closing_time:.1
            size_hint_x:.75
            on_leave:self.state='close'
            MDBoxLayout: 
                id:content
                orientation:'vertical'
                size_hint:1,1
                padding:dp(5)
                spacing:dp(5)
                pos_hint:{'top':1,'center_y':.5}
    Picture:
        id:picture
        name:'picture'
    
    Personal:
        id:personal
        name:'personal'

    ForgotPass:
        id:forgotpass
        name:'forgotpass'

    ChangePassword:
        id:changepass
        name:'changepass'

    Email:
        id:email
        name:'email'

    Phone:
        id:phone
        name:'phone'

    BioRegister:
        id:bioregister
        name:'bioregister'

    New_Wallet:
        id:new_wallet
        name:'new_wallet'

    SavingsScheme:
        id:savings
        name:'savings'
    
    IndividualWallet:
        id:ind_wallet
        name:'ind_wallet'
    
    FamilyWallet:
        id:fam_wallet
        name:'fam_wallet'
    
    Notifications:
        id:notification
        name:'notification'

    WalletHome:
        id:wallethome
        name:'wallethome'
        
<NoInternet@MDScreen>:
    MDBoxLayout:
        size_hint:1,.45
        orientation:'vertical'
        spacing:5 
        halign:'center'
        valign:'center'
        pos_hint:{'center_x':.5,'center_y':.5}
        MDIconButton:
            icon:'cloud-off-outline'
            user_font_size:'70sp'
            halign:'center'
            pos_hint:{'center_x':.5}
        MDLabel:
            text:'Unable to connect to database.\nCheck your Internet Connection and try again'
            font_size:16 
            halign:'center'
            size_hint:.9,.5
            pos_hint:{'center_x':.5}        

<Login@MDScreen>:
    MDBoxLayout:
        orientation:'vertical'
        size_hint:1,1
        padding:[0,0,0,10]
        pos_hint:{'center_x':.5,'center_y':.5}
        FitImage:
            source:'pics/login.png'
            size_hint:1,.5
            radius:0,0,15,15
            pos_hint:{'center_x':.5,'center_y':.5}
        MDBoxLayout:
            size_hint:1,.5
            spacing:dp(15)
            orientation:'vertical'
            pos_hint:{'center_x':.5,'center_y':.5}
            MDLabel:
                text:'Welcome'
                size_hint:.6,.15
                pos_hint:{'center_x':.5,'center_y':.5}
            CupertinoTextField:
                id:user_email
                size_hint:.6,.18
                hint_text:'Username / Email'
                pos_hint:{'center_x':.5,'center_y':.5}
            PasswordText:
                id:password
                size_hint:.6,.19
                pos_hint:{'center_x':.5,'center_y':.5}
            MDFillRoundFlatButton:
                id:login
                size_hint:.6,.2
                text:'Login'
                pos_hint:{'center_x':.5,'center_y':.5}
                on_release:app.root.change_screen('home')
            MDFlatButton:
                id:forgotpass
                size_hint:.6,.1
                text:'Forgot Password?'
                on_release:app.root.change_screen('forgotpass')
                pos_hint:{'center_x':.5,'center_y':.5}
                font_size:14
            MDFlatButton:
                id:noaccount:
                size_hint:.6,.1
                text:"Don't have an Account?"
                on_release:app.root.change_screen('personal')
                pos_hint:{'center_x':.5,'center_y':.5}
                font_size:14
<Personal@MDScreen>:
    ScrollView:
        size_hint:.75,.9
        padding:[20,10,10,20]
        do_scroll:False,True
        pos_hint:{'center_x':.5,'center_y':.5}
        MDBoxLayout:
            orientation:'vertical'
            size_hint:1,1.9
            pos_hint:{'center_x':.5}
            spacing:dp(10)            
            MDToolbar:
                title:'Peronal Information'
                md_bg_color:app.bg_color
                pos_hint:{'top':1}
                left_action_items:[['chevron-left',lambda _:app.root.back_screen('login')]]        
            MDLabel:
                text:'Personal Details'
                font_size:13
                pos_hint:{'center_x':.5,'center_y':.5}
                size_hint:.7,.2
            CupertinoTextField:
                id:fname
                hint_text:'First Name'
                size_hint:.9,.2
                pos_hint:{'center_x':.5,'center_y':.5}
            CupertinoTextField:
                id:lname
                hint_text:'Last Name'
                size_hint:.9,.2
                pos_hint:{'center_x':.5,'center_y':.5}
            CupertinoTextField:
                id:oname
                hint_text:'Other Name(s)'
                size_hint:.9,.2
                pos_hint:{'center_x':.5,'center_y':.5}
            MDLabel:
                text:'Gender'
                font_size:13
                pos_hint:{'center_x':.5,'center_y':.5}
                size_hint:.6,.1
            MDBoxLayout:
                orientation:'horizontal'
                size_hint:.9,.2
                Choice:
                    id:male
                    text:'Male'
                    group:'gender'
                Choice:
                    id:female
                    text:'Female'
                    group:'gender'
            MDFillRoundFlatIconButton:
                id:dob
                icon:'calendar'
                text:'Select Date of Birth'
                size_hint:.9,.23
                pos_hint:{'center_x':.5,'center_y':.5}
                date:None
                on_release:app.root.open_dob()
            CodeNum:
                id:nin
                hint_text:'National Identification Number'
                size_hint:.9,.2
                input_filter:'int'
                max_text_length:11
                pos_hint:{'center_x':.5,'center_y':.5}
            MDLabel:
                text:'Contact Details'
                font_size:13
                pos_hint:{'center_x':.5,'center_y':.5}
                size_hint:.7,.2
            CupertinoTextField:
                id:email
                hint_text:'Email Address'
                size_hint:.9,.2
                pos_hint:{'center_x':.5,'center_y':.5}
            MDBoxLayout:
                orientation:'horizontal'
                size_hint:.9,.2
                spacing:dp(10)
                MDIconButton:
                    id:iso
                    icon:'pics/ng.png'
                    user_font_size:'8sp'
                    value:234
                    size_hint_x:.2
                    pos_hint:{'center_y':.5}
                CodeNum:
                    id:phone
                    input_filter:'int'
                    max_text_length:14
                    size_hint_x:.7
                    hint_text:'Phone Number'
                    pos_hint:{'center_y':.5}
            PasswordText:
                id:password
                size_hint:.9,.2
                pos_hint:{'center_x':.5,'center_y':.5}
            CupertinoTextField:
                id:confirm_password
                password:True
                hint_text:'Confirm Password'
                size_hint:.9,.2
                pos_hint:{'center_x':.5,'center_y':.5}
            MDLabel:
                text:'Home Address'
                font_size:13
                pos_hint:{'center_x':.5,'center_y':.5}
                size_hint:.7,.2                
            CupertinoTextField:
                id:street
                hint_text:'Street Line'
                size_hint:.9,.4
                multiline:True
                pos_hint:{'center_x':.5,'center_y':.5}
            CupertinoTextField:
                id:state
                hint_text:'State'
                size_hint:.9,.2
                pos_hint:{'center_x':.5,'center_y':.5}
            MDFillRoundFlatIconButton:
                id:country
                icon:'earth'
                text:'Nigeria'
                size_hint:.9,.23
                pos_hint:{'center_x':.5,'center_y':.5}
            MDFillRoundFlatButton:
                id:next
                text:'Next'
                size_hint:.9,.25
                pos_hint:{'center_x':.5,'center_y':.5}
                on_release:app.root.change_screen('picture')
<Picture@MDScreen>:
    MDBoxLayout:
        orientation:'vertical'
        size_hint:.8,.85
        pos_hint:{'center_x':.5,'center_y':.5}
        MDToolbar:
            title:'Upload Picture'
            md_bg_color:app.bg_color
            pos_hint:{'top':1}
            left_action_items:[['chevron-left',lambda _:app.root.back_screen('personal')]] 
        MDLabel:
            text:'Click Image below to  recent Picture of yourself.'
            pos_hint:{'center_x':.5,'center_y':.5}
        UploadPhoto:
            id:image
            source:'pics/account.png'
            radius:[15]
            size_hint:.8,.8
            pos_hint:{'center_x':.5,'center_y':.5}
            on_release:app.root.choose_photo()            
        MDLabel:
            text:'Image should not be older than 6 month of current appearance'
            pos_hint:{'center_x':.5,'center_y':.5}
        MDFillRoundFlatButton:
            id:upload
            text:'Upload'
            size_hint:.9,.25
            pos_hint:{'center_x':.5,'center_y':.5}
            on_release:app.root.change_screen('email')
<Email@MDScreen>:
    MDToolbar:
        title:'Verify Email'
        md_bg_color:app.bg_color
        pos_hint:{'top':1}
        left_action_items:[['chevron-left',lambda _:app.root.change_screen('PHONE')]]        
    MDCard:
        size_hint:.8,.6        
        radius:[15]
        padding:20,20,20,20
        spacing:10
        pos_hint:{'center_x':.5,'center_y':.6}
        MDGridLayout:                    
            cols:1
            spacing:15
            padding:30,20,30,20
            size_hint:.9,1
            pos_hint:{'center_x':.5,'center_y':.5}
            MDLabel:
                text:'Enter Verification Code sent to your Email'
                font_size:14
                size_hint_x:.9
                halign:'center'
            CupertinoTextField:
                id:verifycod
                hint_text:'Verification Code'
                size_hint:.9,.25
                halign:'center'                 
            CupertinoButton:
                id:verify
                text:'Verify'
                size_hint:.4,.2
                on_release:app.root.change_screen('phone')
                halign:'center'            
<Phone@MDScreen>:
    ##md_bg_color:app.back_light
    MDToolbar:
        title:'Verify Phone Number'
        md_bg_color:app.bg_color
        pos_hint:{'top':1}
        left_action_items:[['chevron-left',lambda _:app.root.change_screen('new_wallet')]]
    MDCard:
        size_hint:.8,.6        
        radius:[15]
        padding:20,20,20,20
        spacing:10
        pos_hint:{'center_x':.5,'center_y':.6}
        MDGridLayout:                    
            cols:1
            spacing:15
            padding:30,20,30,20
            size_hint:.9,1
            pos_hint:{'center_x':.5,'center_y':.5}
            MDLabel:
                text:'Enter Verification Code sent to your Phone Number'
                font_size:14
                size_hint_x:.9
                halign:'center'
            CupertinoTextField:
                id:verifycod
                hint_text:'Verification Code'
                size_hint:.9,.4                 
                halign:'center'
            CupertinoButton:
                id:verify
                text:'Verify'
                size_hint:.5,.3
                on_release:app.root.change_screen('new_wallet')            
<New_Wallet@MDScreen>:
    MDBoxLayout:
        orientation:'vertical'
        spacing:dp(20)
        size_hint:.8,.6
        pos_hint:{'center_x':.5,'center_y':.5}
        MDToolbar:
            title:'Create Wallet'
            md_bg_color:app.bg_color
            pos_hint:{'top':1}
            left_action_items:[['chevron-left',lambda _:app.root.back_screen('picture')]]        
        MDCard:
            id:individual
            size_hint:1,.5            
            radius:15
            md_bg_color:1,1,1,1
            pos_hint:{'center_x':.5,'center_y':.5}
            on_release:app.root.change_screen('ind_wallet')
            MDBoxLayout:                
                orientation:'horizontal'
                size_hint:1,1
                padding:20,20,20,20
                MDLabel:
                    text:'Individual'
                    size_hint:.8,.6
                    pos_hint:{'center_x':.5,'center_y':.5}
                MDIcon:
                    id:icon_ind
                    size_hint:.2,.6
                    icon:'chevron-right'
                    pos_hint:{'center_x':.5,'center_y':.5}
        MDCard:
            id:family
            size_hint:1,.5 
            radius:15
            md_bg_color:1,1,1,1           
            pos_hint:{'center_x':.5,'center_y':.5}
            on_release:app.root.change_screen('fam_wallet')
            MDBoxLayout:                
                orientation:'horizontal'
                size_hint:1,1
                padding:20,20,20,20
                MDLabel:
                    text:'Family (Optional)'
                    size_hint:.8,.6
                    pos_hint:{'center_x':.5,'center_y':.5}
                MDIcon:
                    id:icon_fam
                    icon:'chevron-right'   
                    size_hint:.2,.3     
                    pos_hint:{'center_x':.5,'center_y':.5}
        MDFillRoundFlatButton:
            id:create
            on_release:app.root.change_screen('savings')
            text:'Next'
            size_hint:.9,.425
<IndividualWallet@MDScreen>:
    MDBoxLayout:
        orientation:'vertical'
        spacing:dp(20)
        size_hint:.8,.6
        pos_hint:{'center_x':.5,'center_y':.5}
        MDToolbar:
            title:'Individual Wallet'
            md_bg_color:app.bg_color
            pos_hint:{'top':1}
            left_action_items:[['chevron-left',lambda _:app.root.back_screen('new_wallet')]]        
        MDLabel:
            id:name
            #text:f'Name: {app.root.ids.personal.ids.fname.strip()} {app.root.ids.personal.ids.lname.strip()} {app.root.ids.personal.ids.oname.strip()}'
            size_hint:.9,.45
            pos_hint:{'center_x':.5,'center_y':.5}
        MDLabel:
            text:'Enter your BVN and a secret 4 digit Wallet Pin below'
            size_hint:.9,.2
            pos_hint:{'center_x':.5,'center_y':.5}
        CodeNum:
            id:bvn
            hint_text:'BVN'
            size_hint:.7,.3            
            input_filter:'int'
            max_text_length:11
            pos_hint:{'center_x':.5,'center_y':.5}
        CodeNum
            id:pin
            hint_text:'Wallet Pin'
            size_hint:.7,.3            
            input_filter:'int'
            max_text_length:4
            pos_hint:{'center_x':.5,'center_y':.5}
        MDFillRoundFlatButton:
            id:create
            on_release:app.root.change_screen('create_ind_wallet')
            text:'Create'
            size_hint:.9,.3   
            pos_hint:{'center_x':.5,'center_y':.5}
<FamilyWallet@MDScreen>:
    MDBoxLayout:
        orientation:'vertical'
        spacing:dp(20)
        size_hint:.8,.9
        pos_hint:{'center_x':.5,'center_y':.5}
        MDToolbar:
            title:'Family Wallet'
            md_bg_color:app.bg_color
            pos_hint:{'top':1}
            left_action_items:[['chevron-left',lambda _:app.root.back_screen('new_wallet')]]        
        CupertinoTextField:
            id:fam_name
            hint_text:'Family Name'   
            size_hint:.7,.2 
            pos_hint:{'center_x':.5,'center_y':.5}            
        CodeNum:
            id:pin
            hint_text:'Enter Wallet Pin'            
            size_hint:.7,.2 
            input_filter:'int'
            max_text_length:4
            pos_hint:{'center_x':.5,'center_y':.5}        
        MDLabel:
            text:'Administrator(s)'
            size_hint:.7,.05
            pos_hint:{'center_x':.5,'center_y':.5}        
        RecycleView:
            id: admin_rv
            key_viewclass: 'admin'
            key_size: 'height'                        
            size_hint:.7,.5 
            pos_hint:{'center_x':.5,'center_y':.5}        
            RecycleBoxLayout:
                padding: dp(10)
                spacing:dp(10)
                default_size: None, dp(40)
                default_size_hint: 1, None
                size_hint_y: None
                height: self.minimum_height
                orientation: 'vertical'        
        MDLabel:
            text:'Member(s)'
            size_hint:.7,.05
            pos_hint:{'center_x':.5,'center_y':.5}        
        RecycleView:
            id:member_rv
            key_viewclass: 'member'
            key_size: 'height'  
            size_hint:.7,.5
            pos_hint:{'center_x':.5,'center_y':.5}                              
            RecycleBoxLayout:
                padding: dp(10)
                spacing:dp(10)
                default_size: None, dp(40)
                default_size_hint: 1, None
                size_hint_y: None
                height: self.minimum_height
                orientation: 'vertical'    
        MDFillRoundFlatButton:
            id:create
            on_release:app.root.change_screen('create_fam_wallet')
            text:'Create'
            size_hint:.9,.25
            pos_hint:{'center_x':.5,'center_y':.5}        

<SavingsScheme@MDScreen>:
    ScrollView:
        size_hint:.9,.95
        padding:[20,10,10,20]
        do_scroll:False,True
        pos_hint:{'center_x':.5,'center_y':.5}
        MDBoxLayout:
            orientation:'vertical'
            size_hint:1,1.5
            spacing:dp(10)
            pos_hint:{'center_x':.5}            
            MDToolbar:
                title:'Savings Scheme'
                md_bg_color:app.bg_color
                pos_hint:{'top':1}
                left_action_items:[['chevron-left',lambda _:app.root.back_screen('new_wallet')]]        
            MDLabel:
                text:'How much would you like to save (NGN)?'
                size_hint:.9,.1                
                pos_hint:{'center_x':.5,'center_y':.5}
            MDBoxLayout:            
                spacing:dp(10)
                size_hint:.95,.35                
                pos_hint:{'center_x':.5,'center_y':.5}
                Options:
                    id:option1                    
                    text:'1000'
                    value:1000
                    on_release:app.root.option_choose(self,root.ids.option2,root.ids.option3,root.ids.option4,root.ids.customcost)
                Options:
                    id:option2
                    text:'2000'
                    value:2000
                    on_release:app.root.option_choose(self,root.ids.option1,root.ids.option3,root.ids.option4,root.ids.customcost)
                Options:
                    id:option3
                    text:'5000'
                    value:5000
                    on_release:app.root.option_choose(self,root.ids.option1,root.ids.option2,root.ids.option4,root.ids.customcost)
                Options:
                    id:option4
                    text:'10000'
                    value:10000
                    on_release:app.root.option_choose(self,root.ids.option1,root.ids.option2,root.ids.option3,root.ids.customcost)
            MDBoxLayout:            
                spacing:dp(10)     
                size_hint:.65,.35                           
                pos_hint:{'left':1,'center_y':.5}
                Options:
                    id:customcost
                    text:'Custom'
                    value:0
                    textfield:root.ids.camount
                    size_hint:.3,.8                    
                    on_release:
                        app.root.option_choose(self,root.ids.option1,root.ids.option2,root.ids.option3,root.ids.option4)
                        app.root.custom_open(self,root.ids.camount)
                CupertinoTextField:
                    id:camount
                    hint_text:'Enter Custom Amount'
                    input_filter:'int'
                    size_hint:.7,.8                    
                    disabled:True
            MDLabel:
                text:'How often?'
                size_hint:.7,.1                    
                pos_hint:{'center_x':.5,'center_y':.5}
            MDBoxLayout:
                orientation:'horizontal'
                spacing:dp(10)
                size_hint:.95,.35  
                pos_hint:{'center_x':.5,'center_y':.5}
                Options:
                    id:daily                   
                    text:'Daily'
                    value:1
                    on_release:app.root.option_daily(self,root.ids.weekly,root.ids.monthly,root.ids.once)
                Options:
                    id:weekly
                    text:'Weekly'
                    value:7
                    on_release:app.root.option_daily(self,root.ids.daily,root.ids.monthly,root.ids.once)
                Options:
                    id:monthly
                    text:'Monthly'
                    value:31
                    on_release:app.root.option_daily(self,root.ids.weekly,root.ids.daily,root.ids.once)
                Options:
                    id:once
                    text:'One Off'
                    value:0
                    on_release:app.root.option_daily(self,root.ids.weekly,root.ids.monthly,root.ids.daily)
            MDLabel:
                text:'For how long?'
                size_hint:.5,.1
                pos_hint:{'center_x':.5,'center_y':.5}
            MDBoxLayout:
                orientation:'horizontal'
                spacing:dp(10)
                size_hint:.95,.35  
                pos_hint:{'center_x':.5,'center_y':.5}
                Options:
                    id:month3                    
                    text:'3 Months'
                    value:3
                    on_release:app.root.option_choose(self,root.ids.month6,root.ids.month9,root.ids.customtime)
                Options:
                    id:month6
                    text:'6 Months'
                    value:6
                    on_release:app.root.option_choose(self,root.ids.month3,root.ids.month9,root.ids.customtime)
                Options:
                    id:month9
                    text:'9 Months'
                    value:9
                    on_release:app.root.option_choose(self,root.ids.month3,root.ids.month6,root.ids.customtime)
            MDBoxLayout:            
                spacing:dp(10)                
                size_hint:.65,.35  
                pos_hint:{'left':1,'center_y':.5}
                Options:
                    id:customtime
                    text:'Custom'
                    value:0
                    textfield:root.ids.ctime
                    size_hint:.3,.8
                    on_release:
                        app.root.option_choose(self,root.ids.month3,root.ids.month6,root.ids.month9)
                        app.root.custom_open(self,root.ids.ctime)
                CupertinoTextField:
                    id:ctime
                    hint_text:'Enter Custom Duration (Months)'
                    size_hint:.7,.8
                    disabled:True
                    input_filter:'int'
            MDFillRoundFlatButton:
                id:create
                text:'Create'
                size_hint:.9,.3
                pos_hint:{'center_x':.5,'center_y':.5}
                on_release:app.root.change_screen('bioregister')
<Family@MDScreen>:
    MDBoxLayout:
        orientation:'vertical'
        size_hint:1,1
        MDBoxLayout:
            orientation:'horizontal'
            MDIconButton:
                id:back
                icon:'chevron-left'
            MDLabel:
                text:'Family Account'
        CupertinoTextField:
            id:name
            hint_text:'Family Name'
        MDLabel:
            text:'Administrator'
        #BOXFOR ADMIN INCLUDING USER
        MDLabel:
            text:'Members'
        #BOX FOR MEMEBERS
        MDFillRoundFlatButton:
            id:next
            text:'Next'

<BioRegister@MDScreen>:
    MDBoxLayout:
        orientation:'vertical'
        size_hint:1,.9
        spacing:dp(10)
        pos_hint:{'center_x':.5,'center_y':.5}                
        Header:
            title:'Bio Medical Registration'
            prev:'savings'
            size_hint:.7,.2                
            pos_hint:{'center_x':.5,'center_y':.5}                
        MDLabel:
            text:'Select your desired Hospital, Date, Time and Reason for Appointment'
            size_hint:.7,.25                
            pos_hint:{'center_x':.5,'center_y':.5}
        MDRoundFlatButton:
            id:hospital
            text:'Select Hospital'
            size_hint:.7,.2                           
            pos_hint:{'center_x':.5,'center_y':.5}
            on_release:app.root.open_hospital()
        MDRoundFlatButton:
            id:date
            text:'Select Date'
            size_hint:.7,.2         
            date:None        
            on_release:app.root.open_appoint_date()
            pos_hint:{'center_x':.5,'center_y':.5}
        MDRoundFlatButton:
            id:time
            text:'Select Time'
            on_release:app.root.open_appoint_time()
            size_hint:.7,.2                
            pos_hint:{'center_x':.5,'center_y':.5}
        MDFillRoundFlatButton:
            id:book
            text:'Book Appointment'
            size_hint:.7,.2                
            pos_hint:{'center_x':.5,'center_y':.5}
            on_release:app.root.change_screen('homebuild')
<ForgotPass@MDScreen>:
    MDBoxLayout:
        orientation:'vertical'
        size_hint:.8,.5
        pos_hint:{'center_x':.5,'center_y':.6}
        Header:
            title:"Forgot Password"
            prev:'login'
            size_hint:.7,.2                
            pos_hint:{'center_x':.5,'center_y':.5}
        CupertinoTextField:
            id:user_email
            size_hint:.6,.15
            hint_text:'Enter Username or Email'
            pos_hint:{'center_x':.5,'center_y':.5}
        MDFillRoundFlatButton:
            id:send_code
            size_hint:.6,.15
            text:'Send Code'
            pos_hint:{'center_x':.5,'center_y':.5}
            on_release:app.root.change_screen('changepass')
<ChangePassword@MDScreen>:
    MDBoxLayout:
        orientation:'vertical'
        size_hint:1,.7
        pos_hint:{'center_x':.5,'center_y':.5}
        Header:
            title:"Change Password"
            prev:'forgotpass'
            size_hint:.7,.2                
            pos_hint:{'center_x':.5,'center_y':.5}
        CodeNum:
            id:auth
            size_hint:.8,.25
            hint_text:'Access Code'
            pos_hint:{'center_x':.5,'center_y':.7}
        PasswordText:
            id:password
            size_hint:.8,.25
            hint_text:'New Password'
            pos_hint:{'center_x':.5,'center_y':.7}
        CupertinoTextField:
            id:confirm_pass
            password:True
            size_hint:.8,.25
            hint_text:'Confirm Password' 
            pos_hint:{'center_x':.5,'center_y':.7}   
        MDFillRoundFlatButton:
            id:change
            size_hint:.8,.3
            text:'Change'
            pos_hint:{'center_x':.5,'center_y':.5}
            on_release:app.root.change_screen('change_pass_login')
<Home@MDScreen>:    
    MDBottomNavigation:
        id:hometab
        size_hint_y:.9
        active_font_size:dp(10)
        inactive_font_size:dp(10)
        tab_indicator_anim:True    
        DigiTab:
            id:home
            name:'home'
            icon:'home-outline'
            text:'Home'     
            #on_tab_release:app.root.employee_on_tab('vacancy')        
            MDToolbar:
                id:toolbar
                md_bg_color:app.bg_color
                title:'Digi-Clinic'
                pos_hint:{'top':1}
                left_action_items:[['account',lambda _:print('HERE')]]#app.root.open_drawer()]]
                right_action_items:[['bell',lambda _:app.root.change_screen('notification')]]                   
            MDBoxLayout:
                size_hint:1,.83
                pos_hint:{'center_x':.5,'center_y':.44}
                spacing:10
                orientation:'vertical'
                MDSwiper:
                    md_bg_color:app.theme_cls.primary_light
                    items_spacing:dp(10)
                    size_hint:1,.325
                    transition_duration:.1
                    swipe_distance:dp(80)
                    width_mult:1
                    pos_hint:{'center_x':.5,'center_y':.5}
                    MDSwiperItem:
                        size_hint:1,1
                        padding:[10,10,10,10]
                        pos_hint:{'center_x':.5}
                        md_bg_color:app.theme_cls.primary_light
                        MDCard:
                            id:ind_wallet
                            size_hint:1,1
                            padding:10,10,10,10
                            radius:[15,15,15,15]
                            #on_release:app.root.open_info()
                            canvas:
                                Color:
                                    rgba:app.theme_cls.primary_light
                                RoundedRectangle:
                                    radius:[15,15,15,15]
                                    size:self.size
                                    pos:self.pos
                            MDBoxLayout:
                                size_hint:.9,.95
                                orientation:'vertical'
                                spacing:10
                                pos_hint:{'center_x':.5,'center_y':.5}
                                MDLabel:
                                    text:'Individual Balance'
                                    font_size:10
                                    halign:'center'
                                    size_hint:.95,.1
                                    pos_hint:{'center_x':.5}                            
                                MDLabel:
                                    id:amount
                                    halign:'center'
                                    font_size:19
                                    size_hint:.95,.4
                                    text:'NGN0'
                                    pos_hint:{'center_x':.5}                                                    
                    MDSwiperItem:
                        size_hint:1,1
                        padding:[10,10,10,10]
                        pos_hint:{'center_x':-.5}
                        md_bg_color:app.theme_cls.primary_light
                        MDCard:
                            id:fam_wallet
                            size_hint:1,1
                            padding:10,10,10,10
                            radius:[15,15,15,15]
                            #on_release:app.root.open_info()
                            canvas:
                                Color:
                                    rgba:app.theme_cls.primary_light
                                RoundedRectangle:
                                    radius:[15,15,15,15]
                                    size:self.size
                                    pos:self.pos
                            MDBoxLayout:
                                size_hint:.9,.95
                                orientation:'vertical'
                                spacing:10
                                pos_hint:{'center_x':.5,'center_y':.5}
                                MDLabel:
                                    text:'Family Balance'
                                    font_size:10
                                    halign:'center'
                                    size_hint:.95,.1
                                    pos_hint:{'center_x':.5}                            
                                MDLabel:
                                    id:amount
                                    halign:'center'
                                    font_size:19
                                    size_hint:.95,.4
                                    text:'NGN0'
                                    pos_hint:{'center_x':.5}           
                GridLayout:
                    id:grid
                    cols:2
                    rows:2
                    size_hint:.9,1
                    spacing:20
                    pos_hint:{'center_x':.5}
                    HomeCard:
                        id:book_appointment
                        pos_hint:{'center_x':.5}
                        text:'Booking Appointment'
                        icon:'file-plus'
                        on_release:app.root.change_screen('book_appoint')
                    HomeCard:
                        id:telemedicine
                        pos_hint:{'center_x':.5}
                        text:'Telemedicine'
                        icon:'stethoscope'
                        on_release:app.root.change_screen('telemedicine')            
                    HomeCard:
                        id:digicard
                        pos_hint:{'center_x':.5}
                        text:'Digi-Card'
                        icon:'smart-card'
                        on_release:app.root.change_screen('digicard')
                    HomeCard:
                        id:emergency
                        pos_hint:{'center_x':.5}
                        text:'Report Emergency'
                        icon:'ambulance'
                        on_release:app.root.change_screen('emergency')                                
        DigiTab:
            id:appointment
            name:'appointment'
            icon:'file-document-outline'
            text:'Appointments' 
            #on_tab_release:app.root.employee_on_tab('vacancy')        
            RecycleView:
                id: appointment_view
                key_viewclass: 'appointment'
                key_size: 'height'         
                size_hint:.8,.9
                pos_hint:{'center_x':.5,'center_y':.5}               
                RecycleBoxLayout:
                    padding: dp(10)
                    spacing:dp(10)
                    default_size: None, dp(40)
                    default_size_hint: 1, None
                    size_hint_y: None
                    height: self.minimum_height
                    orientation: 'vertical'    
        DigiTab:
            id:profile
            name:'profile'
            icon:'account-outline'
            text:'Profile' 
            #on_tab_release:app.root.employee_on_tab('vacancy')            
            ScrollView:
                size_hint:.8,.825
                pos_hint:{'center_x':.5,'center_y':.5}
                do_scroll:False,True
                scroll_timeout:100
                allow_overscroll:False
                MDBoxLayout:
                    id:profilecard
                    size_hint:1,5                    
                    radius:[15]
                    pos_hint:{'center_x':.5,'center_y':.5}
                    MDGridLayout:                    
                        cols:1
                        spacing:15
                        padding:30,30,30,30
                        size_hint:.1,1
                        pos_hint:{'center_x':.5,'center_y':.5}
                        MDRelativeLayout:
                            size_hint:.9,.87
                            padding:45,0,35,45
                            AccPic:
                                id:accpic
                                user_font_size:'64sp'
                                source:'pics/account.png' 
                                pos_hint:{'center_x':.5,'center_y':.5}                                
                                canvas:
                                    Color:
                                        rgb:1,1,1
                                    Ellipse:
                                        source:accpic.source
                                        angle_start:0
                                        angle_end:360
                                        pos:self.pos
                                        size:self.size        
                        MDLabel:
                            id:name                    
                            text:'Name'
                        MDLabel:
                            id:dob
                            text:'Date of Birth' 
                        MDLabel:
                            id:email
                            text:'Email Address'                                                
                        MDLabel:
                            id:phone
                            text:'Phone Number' 
                        MDLabel:
                            id:address
                            text:'Home Address' 
                        MDLabel:
                            id:marital
                            text:'Marital Status' 
                        MDLabel:
                            id:next_of_kin
                            text:'Next of Kin (Name)' 
                        MDLabel:
                            id:type
                            text:'Type' 
                        MDLabel:
                            id:bg
                            text:'Blood Group'
                        MDLabel:
                            id:genotype
                            text:'Genotype'
                        MDLabel:
                            id:height                    
                            text:'Height'
                        MDLabel:
                            id:weight
                            text:'Weight' 
                        MDLabel:
                            id:email
                            text:'Email Address' 
                        MDLabel:
                            id:health_insurance
                            text:'Health Insurance ID'                                                
                        MDFillRoundFlatButton:
                            id:allergies
                            size_hint:.6,.2
                            text:'Allergies'
                            #pos_hint:{'center_x':.5,'center_y':.5}:                            
                        MDFillRoundFlatButton:
                            id:c_and_d
                            size_hint:.6,.2
                            text:'Challenges and Disablity'
                            #pos_hint:{'center_x':.5,'center_y':.5}:                            

<Notifications@MDScreen>:
<WalletHome@MDScreen>:
<ImageButton>:
<Options@MDCard>:
    text:''
    value:0
    radius:15
    MDLabel:
        text:root.text
        halign:'center'
        pos_hint:{'center_x':.5,'center_y':.5}

<CodeNum@CupertinoTextField>:
    input_filter:'int'

<ImageButton@MDIconButton+AsyncImage>:
<PasswordText@MDBoxLayout>:
    orientation:'horizontal'    
    hint_text:'Password'
    text:root.ids.password.text
    CupertinoTextField:
        id:password
        password:True
        hint_text:root.hint_text
        size_hint:.75,1
    MDTextButton:
        id:showpass
        text:'SHOW'
        halign:'center'
        font_size:12
        size_hint:.2,1
        bold:True
        pos_hint:{'center_y':.5}
        on_release:app.root.change_password(root.ids.password,self)
<Choice@MDBoxLayout>:
    orientation:'horizontal'
    group:''
    text:''
    active:root.ids.box.active
    spacing:dp(10)
    CheckBox:
        id:box
        group:root.group
        
    MDLabel:
        text:root.text
        font_size:13
<Header@MDBoxLayout>:
    title:''
    prev:''
    spacing:dp(5)
    pos_hint:{'top':1}
    orientation:'vertical'
    MDIconButton:
        icon:'chevron-left'
        on_release:app.root.change_screen(root.prev)
    MDLabel:
        text:root.title
<MDScreen>:
    md_bg_color:app.bg_color
<MySnackBar>:
    snackbar_x:'10dp'
    snackbar_y:'70dp'
    bg_color:1,1,1,1
    snackbar_animation_dir:'Left'
    MDIconButton:
        pos_hint:{'center_y':.5}
        icon:root.icon
        size_hint:.1,None
        opposite_colors:True
    MDLabel:
        id:text_bar
        size_hint:.9,None
        height:self.texture_size[1]
        text:root.text
        text_size:self.width,None
        font_size:root.font_size
        theme_text_color:'Custom'        
        shorten:True
        shorten_from:'right'        
        pos_hint:{'center_y':.5}
<ImageCard@MDCard+Image>:
<PersonList@OneLineIconListItem>:
    radius:[15,15,15,15]
    font_style:'Body2'
    padding:dp(0)
    font_size:10
    text:''
    code:''
    address:''
    spacing:dp(0)
    picture:''
    on_release:app.root.change_hospital(app.root.ids.bioregister.ids.hospital,root.text,root.code,app.root.hospitalbuttom)
    IconLeftWidget:
        user_font_size:'16sp'
        icon:root.picture
        pos_hint:{'right':1,'center_y':.5}
<HospitalBox@MDScreen>:
    orientation: "vertical"
    size_hint:.8,None
    pos_hint:{'center_x':.5}
    height: "500dp"
    spacing:"20dp"
    MDBoxLayout:
        orientation: 'vertical'
        spacing: dp(10)
        padding: dp(10)
        height:'20dp'
        MDBoxLayout:
            adaptive_height: True
            MDIconButton:
                icon: 'magnify'
                pos_hint:{'center_y':.5}
            CupertinoTextField:
                id: search_hospital
                hint_text: 'Enter Hospital Name'
                pos_hint:{'center_y':.5}
                on_text:app.root.search_hospital(self.text)        
        RecycleView:
            id: hospitalview
            key_viewclass: 'hospital'
            key_size: 'height'                        
            RecycleBoxLayout:
                padding: dp(10)
                spacing:dp(10)
                default_size: None, dp(40)
                default_size_hint: 1, None
                size_hint_y: None
                height: self.minimum_height
                orientation: 'vertical'        
<HospitalList@OneLineAvatarListItem>:
    size_hint_y:None
    height:30    
    icon:''
    code:''
    address:''
    #on_release:app.root.change_count_name(app.root.ids.new.ids.country,self.text,self.icon,'country',app.root.countrybuttom)
    IconLeftWidget:
        pos_hint:{'center_y':.5}
        user_font_size:'12sp'
        canvas:
            Color:
                rgba:1,1,1,1
            Ellipse:
                source:root.icon
                angle_start:0
                angle_end:360
                pos:self.pos
                size:self.size
<HomeCard@MDCard>:
    radius:[25,25,25,25]
    size_hint:.45,.45
    text:''
    icon:''
    AnchorLayout:        
        size_hint:1,1
        pos_hint:{'center_x':.5,'center_y':.5}        
        spacing:5
        MDIconButton:
            anchor_x:'right'
            anchor_y:'top'
            radius:[25,25,0,0]
            pos_hint:{'top':1,'right':.6}
            icon:root.icon
        MDLabel:
            anchor_x:'center'
            anchor_y:'center'
            text:root.text
            size_hint:.9,.3
            font_size:15
            pos_hint:{'center_x':.6}
<DigiTab@MDBottomNavigationItem>:
    md_bg_color:app.bg_color
<HomeDrawer@MDNavigationDrawer>:
<AccPic@MDIconButton+AsyncImage>:
    line_color:app.theme_cls.primary_light
    line_width:25
<UploadPhoto@MDIconButton+AsyncImage>:
    line_color:app.theme_cls.primary_light
    line_width:25
    user_font_size:'64sp'
    source:''
    pos_hint:{'center_x':.5,'center_y':.5}                
    canvas:
        Color:
            rgb:1,1,1
        RoundedRectangle:
            source:root.source
            radius:[15]
            pos:self.pos
            size:self.size                            
